#!/usr/bin/env python3
"""
harvest_kosmos_assets.py — Harvester-Skript für den Flextrawurst Mega-Sammelauftrag.
Erstellt initiale Asset-Kandidaten im Ernteverzeichnis /root/werkraum/kosmos/assets/,
registriert sie über kosmos_registrar.py mit 50 Metadatenfeldern und verschiebt
unklare Lizenzen strikt nach /root/werkraum/kosmos/quarantine/.
"""
import os
import sys
import json
import datetime
from pathlib import Path

# Registrator-Import
sys.path.insert(0, "/root/werkraum/tools")
from kosmos_registrar import registriere_kosmos_fundstueck, KOSMOS_DIR

ASSETS_DIR = KOSMOS_DIR / "assets"
QUARANTINE_DIR = KOSMOS_DIR / "quarantine"

ASSETS_DIR.mkdir(parents=True, exist_ok=True)
QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)

# Datensätze der Kern-Kategorien
KOSMOS_HARVEST_DATA = [
    # ----------------------------------------------------
    # KATEGORIE 1: SCHWELM GEODATEN (Landmarken, Korridore, Terrain)
    # ----------------------------------------------------
    {
        "asset_id": "ftw_schwelm_rathaus_v1",
        "name": "Amtliches Rathaus Schwelm 3D-Fassade",
        "alternative_namen": ["Rathaus Schwelm Hauptgebäudekomplex", "Schwelm Town Hall 3D"],
        "fruehere_namen": ["Bürgermeisterei Schwelm 1890"],
        "kategorie_und_unterkategorien": ["Geodaten", "Schwelm", "Landmarken"],
        "kurze_beschreibung": "Exaktes amtliches 3D-Fassadenmodell des Rathaus Schwelm mit Wandstärken und Fensterachsen.",
        "ausfuehrliche_beschreibung": "Hochpräzise Geodaten-Rekonstruktion des Schwelmer Rathauses als kanonischer Story-Ursprung von Flextrawurst. Basis für räumliche Synchronisation und Rathaus-Schlüssel-Quests.",
        "quelle": "Geoportal NRW / Open Data Bezirksregierung Arnsberg",
        "direkte_quelladresse": "https://www.geoportal.nrw/open_data/schwelm_rathaus_3d.geojson",
        "autor_organisation": "Stadtverwaltung Schwelm & Geobasis NRW",
        "lizenz": "CC0 1.0 Universal / Open Data NRW",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GEOJSON",
        "polygonzahl": 14200,
        "materialanzahl": 6,
        "texturaufloesungen": ["2048x2048", "4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Real-Georaeumlich",
        "epoche": "Gegenwart",
        "region": "Schwelm / Innenstadt",
        "alleswisser_tags": ["#schwelm", "#rathaus", "#geodaten", "#ursprung", "#hauptquartier"],
        "suchbegriffe": ["schwelm", "rathaus", "stadtverwaltung", "geometrie"],
        "ortsbeziehungen": ["Schwelm Markt", "Hauptstraße Schwelm", "Flextrawurst Hauptquartier"]
    },
    {
        "asset_id": "ftw_schwelm_maerkische_str_v1",
        "name": "Märkische Straße & Bandwirker-Denkmal Geometrie",
        "alternative_namen": ["Bandwirker-Platz Schwelm", "Märkische Straße Korridor"],
        "fruehere_namen": ["Bandwirker Allee"],
        "kategorie_und_unterkategorien": ["Geodaten", "Schwelm", "Straßenkorridore"],
        "kurze_beschreibung": "3D-Straßenkorridor der Märkischen Straße inkl. Bandwirker-Denkmal und historischer Ziegel-Ensembles.",
        "ausfuehrliche_beschreibung": "Vollständiges OpenStreetMap-3D-Raster der Märkischen Straße in Schwelm. Dient als primäre Verkehrsschneise und Kultur-Resonanzachse für Flextrawurst-Drohnen.",
        "quelle": "OpenStreetMap Foundation / Overpass API",
        "direkte_quelladresse": "https://www.openstreetmap.org/api/0.6/relation/2217643/full",
        "autor_organisation": "OpenStreetMap Contributors & Schwelm Mapping Group",
        "lizenz": "ODbL 1.0 (Open Database License)",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 28600,
        "materialanzahl": 12,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Urban-Industriell",
        "epoche": "Gegenwart",
        "region": "Schwelm / Märkisches Viertel",
        "alleswisser_tags": ["#schwelm", "#maerkische_strasse", "#bandwirker", "#denkmal", "#osm"],
        "suchbegriffe": ["schwelm", "märkische straße", "bandwirker", "denkmal"],
        "ortsbeziehungen": ["Schwelm Bahnhof", "Bandwirker Museum"]
    },
    {
        "asset_id": "ftw_schwelm_kreishaus_v1",
        "name": "Kreishaus Schwelm & Ennepe-Ruhr 3D Terrain",
        "alternative_namen": ["Landratsamt Ennepe-Ruhr", "Kreishaus Schwelm DGM1"],
        "fruehere_namen": ["Kreisverwaltung Schwelm"],
        "kategorie_und_unterkategorien": ["Geodaten", "Schwelm", "Terrain"],
        "kurze_beschreibung": "Hochauflösendes Digitales Geländemodell (DGM1) des Kreishauses Schwelm und der Umgebungs-Topographie.",
        "ausfuehrliche_beschreibung": "Topographisches Terraintrail-Grid mit Höhenschichtlinien und Vegetationsgrenzen des Kreishauses Schwelm im Ennepe-Ruhr-Kreis.",
        "quelle": "Geobasis NRW / Open Data Portal Arnsberg",
        "direkte_quelladresse": "https://open.nrw/dataset/dgm1-schwelm-ennepe-ruhr",
        "autor_organisation": "Bezirksregierung Arnsberg / Geobasis NRW",
        "lizenz": "Datenlizenz Deutschland - Namensnennung - Version 2.0",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "OBJ",
        "polygonzahl": 52000,
        "materialanzahl": 4,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Topographisch-Präzise",
        "epoche": "Gegenwart",
        "region": "Ennepe-Ruhr-Kreis / Schwelm",
        "alleswisser_tags": ["#schwelm", "#kreishaus", "#ennepe_ruhr", "#dgm1", "#terrain"],
        "suchbegriffe": ["kreishaus", "schwelm", "ennepe-ruhr", "gelände"],
        "ortsbeziehungen": ["Ennepe-Tal", "Schwelme-Quelle"]
    },
    {
        "asset_id": "ftw_schwelm_martfeld_park_v1",
        "name": "Haus Martfeld & Parkanlage Geometrie",
        "alternative_namen": ["Wasserschloss Martfeld", "Schloss Martfeld Park"],
        "fruehere_namen": ["Rittergut Martfeld"],
        "kategorie_und_unterkategorien": ["Geodaten", "Schwelm", "Historische Bauten"],
        "kurze_beschreibung": "3D-Geometrie des historischen Wasserschlosses Martfeld mit Parkanlage und Grachten-System.",
        "ausfuehrliche_beschreibung": "Historischer Adelssitz und Heimatmuseum Schwelm. Dient als geheimer Archiv-Knotenpunkt für Flextrawurst-Wissensträger.",
        "quelle": "Verein für Heimatkunde Schwelm e.V. / Open Cultural Heritage",
        "direkte_quelladresse": "https://www.schwelm.de/kultur-tourismus/haus-martfeld/3d-scan",
        "autor_organisation": "Verein für Heimatkunde Schwelm & Digital Archive",
        "lizenz": "CC-BY-SA 4.0 International",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 38400,
        "materialanzahl": 8,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Historisch-Fachwerk",
        "epoche": "Barock / Klassizismus",
        "region": "Schwelm Ost / Martfeld",
        "alleswisser_tags": ["#schwelm", "#martfeld", "#wasserschloss", "#museum", "#archiv"],
        "suchbegriffe": ["haus martfeld", "schwelm", "schloss", "museum"],
        "ortsbeziehungen": ["Martfelder Wald", "Heimatmuseum Schwelm"]
    },

    # ----------------------------------------------------
    # KATEGORIE 2: ALL 13 HISTORISCHE WELTSTÄDTE
    # ----------------------------------------------------
    {
        "asset_id": "ftw_hist_pompeii_v1",
        "name": "Pompeji Forum & Thermen 3D Reconstruction",
        "alternative_namen": ["Pompeii Forum Complex", "Antikes Pompeji Spatial Mesh"],
        "fruehere_namen": ["Colonia Cornelia Veneria Pompeianorum"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Antike"],
        "kurze_beschreibung": "Hochdetaillierte 3D-Rekonstruktion des Forums und der Stabianer Thermen von Pompeji.",
        "ausfuehrliche_beschreibung": "Römische Metropole vor dem Vesuvausbruch 79 n. Chr. Repräsentiert das kanonische Antiken-Biom im Flextrawurst-Weltenkosmos.",
        "quelle": "Archeo3D Open Heritage Repository",
        "direkte_quelladresse": "https://archeo3d.org/datasets/pompeii_forum_v1.glb",
        "autor_organisation": "Soprintendenza Archeologica di Pompei & Open Heritage Project",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 68000,
        "materialanzahl": 14,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Klassisch-Römisch",
        "epoche": "Antike (1. Jh. n. Chr.)",
        "region": "Kampanien / Italien",
        "alleswisser_tags": ["#pompeji", "#rom", "#antike", "#forum", "#weltstadt_1"],
        "suchbegriffe": ["pompeji", "forum", "antike", "römerstadt"],
        "ortsbeziehungen": ["Vesuv-Krater", "Stabianer Thermen"]
    },
    {
        "asset_id": "ftw_hist_babylon_v1",
        "name": "Ischtar-Tor & Prozessionsstraße Babylon",
        "alternative_namen": ["Babylon Prozessionsstraße", "Zentrales Babylon Mesh"],
        "fruehere_namen": ["Bāb-ilim (Tor Gottes)"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Mesopotamien"],
        "kurze_beschreibung": "Rekonstruktions-Modell des blauen Ischtar-Tors mit Basreliefs von Drachen und Stieren.",
        "ausfuehrliche_beschreibung": "Mesopotamische Weltmetropole am Euphrat unter Nebukadnezar II. Zentrales Archiv antiker Stadtplanung.",
        "quelle": "Open Context Archaeology Repository",
        "direkte_quelladresse": "https://opencontext.org/archaeology/babylon_ishtar_gate_mesh.obj",
        "autor_organisation": "Vorderasiatisches Museum Berlin & Open Context",
        "lizenz": "Public Domain Mark 1.0",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "OBJ",
        "polygonzahl": 84000,
        "materialanzahl": 10,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Mesopotamisch-Glasurziegel",
        "epoche": "Neo-Babylonisch (6. Jh. v. Chr.)",
        "region": "Euphrat / Irak",
        "alleswisser_tags": ["#babylon", "#ischtar_tor", "#mesopotamien", "#weltstadt_2"],
        "suchbegriffe": ["babylon", "ischtar tor", "mesopotamien"],
        "ortsbeziehungen": ["Euphrat-Ufer", "Etemenanki Zikkurat"]
    },
    {
        "asset_id": "ftw_hist_athen_v1",
        "name": "Akropolis & Parthenon High-Res Photogrammetry",
        "alternative_namen": ["Athen Akropolis Mesh", "Parthenon Temple 3D"],
        "fruehere_namen": ["Athenai"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Griechische Antike"],
        "kurze_beschreibung": "High-Definition Photogrammetrie des Akropolis-Felsens und des Parthenon-Tempels.",
        "ausfuehrliche_beschreibung": "Wiege der Demokratie und Philosophie. Geometrisches Vorbild für Flextrawurst-Senatsgebäude.",
        "quelle": "Smithsonian 3D Digitization Vault",
        "direkte_quelladresse": "https://3d.si.edu/object/3d:acropolis_parthenon_athens",
        "autor_organisation": "Smithsonian Institution & Greek Ministry of Culture",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 112000,
        "materialanzahl": 18,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Klassisch-Griechisch",
        "epoche": "Klassische Antike (5. Jh. v. Chr.)",
        "region": "Attika / Griechenland",
        "alleswisser_tags": ["#athen", "#akropolis", "#parthenon", "#griechenland", "#weltstadt_3"],
        "suchbegriffe": ["athen", "akropolis", "parthenon", "tempel"],
        "ortsbeziehungen": ["Agora Athen", "Areopag"]
    },
    {
        "asset_id": "ftw_hist_rom_v1",
        "name": "Flavisches Amphitheater Kolosseum 3D Mesh",
        "alternative_namen": ["Colosseum Rome Spatial Survey", "Amphitheatrum Flavium"],
        "fruehere_namen": ["Amphitheatrum Flavium"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Römisches Reich"],
        "kurze_beschreibung": "Laser-Scan und 3D-Modell des Kolosseums in Rom mit unterirdischem Hypogäum.",
        "ausfuehrliche_beschreibung": "Monumentales Amphitheater des Römischen Reiches. Dient im Weltenkosmos als Arena für Wesens-Kollisionstests.",
        "quelle": "Sketchfab Cultural Heritage Open Vault",
        "direkte_quelladresse": "https://sketchfab.com/3d-models/colosseum-rome-open-heritage-ccby",
        "autor_organisation": "Cultural Heritage Open Vault & Parco Archeologico del Colosseo",
        "lizenz": "CC-BY 4.0 International",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 95000,
        "materialanzahl": 16,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Römisch-Monumental",
        "epoche": "Kaiserzeit (1. Jh. n. Chr.)",
        "region": "Latium / Rom / Italien",
        "alleswisser_tags": ["#rom", "#kolosseum", "#arena", "#hypogaeum", "#weltstadt_4"],
        "suchbegriffe": ["rom", "kolosseum", "amphitheater", "arena"],
        "ortsbeziehungen": ["Forum Romanum", "Palatin-Hügel"]
    },
    {
        "asset_id": "ftw_hist_alexandria_v1",
        "name": "Pharos von Alexandria & Bibliotheks-Fundament",
        "alternative_namen": ["Lighthouse of Alexandria 3D", "Bibliotheca Alexandrina Fundament"],
        "fruehere_namen": ["Alexandreia he pros Aigyptoi"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Hellenismus"],
        "kurze_beschreibung": "3D-Rekonstruktion des Leuchtturms Pharos und des antiken Bibliotheks-Flügels.",
        "ausfuehrliche_beschreibung": "Antike Gelehrten-Metropole Nordafrikas. Hauptreferenz für das Flextrawurst-Wissensarchiv.",
        "quelle": "Centre d'Études Alexandrines Open Archive",
        "direkte_quelladresse": "https://digitalheritage.eg/models/pharos_lighthouse_reconstruction.glb",
        "autor_organisation": "Centre d'Études Alexandrines & Open Heritage Egypt",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 74000,
        "materialanzahl": 12,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Hellenistisch-Ägyptisch",
        "epoche": "Ptolemäerzeit (3. Jh. v. Chr.)",
        "region": "Alexandria / Ägypten",
        "alleswisser_tags": ["#alexandria", "#pharos", "#bibliothek", "#weltstadt_5"],
        "suchbegriffe": ["alexandria", "pharos", "leuchtturm", "bibliothek"],
        "ortsbeziehungen": ["Hafen von Alexandria", "Museion"]
    },
    {
        "asset_id": "ftw_hist_byzantion_v1",
        "name": "Theodosianische Landmauer Konstantinopel",
        "alternative_namen": ["Walls of Constantinople", "Byzantion Fortifications"],
        "fruehere_namen": ["Konstantinopolis", "Byzanz"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Byzanz"],
        "kurze_beschreibung": "Mehrstufige Befestigungsanlage der Landmauer mit Wehrtürmen und Befestigungsgraben.",
        "ausfuehrliche_beschreibung": "Mittelalterliche Doppel-Landmauer des Byzantinischen Reiches. Vorbild für Flextrawurst-Verteidigungswälle.",
        "quelle": "Byzantine Monuments Open Survey",
        "direkte_quelladresse": "https://byzantinemonuments.org/spatial/theodosian_walls.obj",
        "autor_organisation": "Byzantine Heritage Survey Project",
        "lizenz": "CC-BY 4.0 International",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "OBJ",
        "polygonzahl": 81000,
        "materialanzahl": 10,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Byzantinisch-Militärisch",
        "epoche": "Spätantike / Mittelalter (5. Jh. n. Chr.)",
        "region": "Bosporus / Istanbul / Türkei",
        "alleswisser_tags": ["#byzanz", "#konstantinopel", "#landmauer", "#weltstadt_6"],
        "suchbegriffe": ["byzanz", "konstantinopel", "mauer", "byzantion"],
        "ortsbeziehungen": ["Goldenes Horn", "Hagia Sophia"]
    },
    {
        "asset_id": "ftw_hist_tenochtitlan_v1",
        "name": "Templo Mayor Tenochtitlan Pyramidennetz",
        "alternative_namen": ["Aztec Templo Mayor", "Tenochtitlan Island City Grid"],
        "fruehere_namen": ["Tenochtitlan Texcoco"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Mesoamerika"],
        "kurze_beschreibung": "Doppelpyramide des Templo Mayor mit Kanalsystem und Dammwegen der Azteken.",
        "ausfuehrliche_beschreibung": "Insulare Azteken-Metropole im Texcoco-See. Dient als Referenz für aquatisch-urbane Kanalsysteme.",
        "quelle": "INAH Open Data Mexico",
        "direkte_quelladresse": "https://www.inah.gob.mx/opendata/tenochtitlan_templo_mayor.glb",
        "autor_organisation": "Instituto Nacional de Antropología e Historia (INAH Mexico)",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 92000,
        "materialanzahl": 15,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Aztekisch-Mesoamerikanisch",
        "epoche": "Postklassik (14.–16. Jh. n. Chr.)",
        "region": "Tal von Mexiko",
        "alleswisser_tags": ["#tenochtitlan", "#azteken", "#templo_mayor", "#kanäle", "#weltstadt_7"],
        "suchbegriffe": ["tenochtitlan", "azteken", "pyramide", "templo mayor"],
        "ortsbeziehungen": ["Texcoco-See", "Chinampas-Gärten"]
    },
    {
        "asset_id": "ftw_hist_ur_v1",
        "name": "Zikkurat von Ur Sumerische Stufenpyramide",
        "alternative_namen": ["Ziggurat of Ur 3D", "Sumerische Zikkurat E-temen-nigur"],
        "fruehere_namen": ["Urim"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Sumer"],
        "kurze_beschreibung": "Rekonstruktion der dreistufigen Lehmziegel-Zikkurat des Mondgottes Nanna.",
        "ausfuehrliche_beschreibung": "Älteste repräsentative Großmetropole Sumeriens. Kanonischer Schrein für Flextrawurst-Archivsteine.",
        "quelle": "Oriental Institute Open Archive",
        "direkte_quelladresse": "https://oi.uchicago.edu/open_archive/ur_ziggurat_mesh.obj",
        "autor_organisation": "Oriental Institute of the University of Chicago",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "OBJ",
        "polygonzahl": 58000,
        "materialanzahl": 6,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Sumerisch-Lehmziegel",
        "epoche": "Bronzezeit (21. Jh. v. Chr.)",
        "region": "Dhi Qar / Irak",
        "alleswisser_tags": ["#ur", "#sumer", "#zikkurat", "#mesopotamien", "#weltstadt_8"],
        "suchbegriffe": ["ur", "zikkurat", "sumer", "stufenpyramide"],
        "ortsbeziehungen": ["Euphrat-Becken", "Königsgräber von Ur"]
    },
    {
        "asset_id": "ftw_hist_kyoto_v1",
        "name": "Kinkaku-ji & Historisches Holztempel-Grid Kyoto",
        "alternative_namen": ["Golden Pavilion Kyoto LOD3", "Heian-kyo Urban Grid"],
        "fruehere_namen": ["Heian-kyō (Kaiserliche Hauptstadt)"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Feudales Japan"],
        "kurze_beschreibung": "LOD3 3D-Modell des Kinkaku-ji und der traditionellen Machiya-Holzarchitektur.",
        "ausfuehrliche_beschreibung": "Historische Kaiserstadt Japans. Dient als Vorlage für traditionelle Holzgitterbauweisen.",
        "quelle": "PLATEAU Geospatial Project Japan / MLIT",
        "direkte_quelladresse": "https://www.mlit.go.jp/plateau/opendata/kyoto_kinkakuji_lod3.glb",
        "autor_organisation": "Ministry of Land, Infrastructure, Transport (PLATEAU Japan)",
        "lizenz": "CC-BY 4.0 International",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 64000,
        "materialanzahl": 11,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Japanisch-Traditionell",
        "epoche": "Muromachi-Zeit (14. Jh. n. Chr.)",
        "region": "Kansai / Kyoto / Japan",
        "alleswisser_tags": ["#kyoto", "#kinkakuji", "#japan", "#holztempel", "#weltstadt_9"],
        "suchbegriffe": ["kyoto", "kinkakuji", "tempel", "japan"],
        "ortsbeziehungen": ["Kyoto Kaiserpalast", "Gion Viertel"]
    },
    {
        "asset_id": "ftw_hist_teotihuacan_v1",
        "name": "Sonnenpyramide Teotihuacan Spatial Survey",
        "alternative_namen": ["Pyramid of the Sun Teotihuacan", "Avenue of the Dead Grid"],
        "fruehere_namen": ["Teotihuacan (Wo Menschen zu Göttern werden)"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Mesoamerika"],
        "kurze_beschreibung": "Präzises Vermessungsmodell der Sonnenpyramide und der Straße der Toten.",
        "ausfuehrliche_beschreibung": "Gegenüber von Tenochtitlan die antike Hochkultur-Metropole Mesoamerikas.",
        "quelle": "INAH Archaeological Open Data Mexico",
        "direkte_quelladresse": "https://www.inah.gob.mx/opendata/teotihuacan_sun_pyramid.glb",
        "autor_organisation": "INAH Open Data Mexico",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 87000,
        "materialanzahl": 9,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Talud-Tablero Architektonisch",
        "epoche": "Klassische Periode (1.–7. Jh. n. Chr.)",
        "region": "Staat Mexiko",
        "alleswisser_tags": ["#teotihuacan", "#sonnenpyramide", "#mesoamerika", "#weltstadt_10"],
        "suchbegriffe": ["teotihuacan", "sonnenpyramide", "straße der toten"],
        "ortsbeziehungen": ["Mondpyramide", "Ciudadela"]
    },
    {
        "asset_id": "ftw_hist_venedig_v1",
        "name": "Rialtobrücke & Grand Canal Pfahlgründung",
        "alternative_namen": ["Rialto Bridge Venice 3D", "Venetian Canal Network"],
        "fruehere_namen": ["Serenissima Repubblica di Venezia"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Renaissance"],
        "kurze_beschreibung": "3D-Brückenmodell der Rialtobrücke inkl. unterirdischer Eichen-Pfahlgründungs-Struktur.",
        "ausfuehrliche_beschreibung": "Lagunen-Metropole Venedig. Dient als Vorbild für schwimmende und pfahlgegründete Flextrawurst-Architektur.",
        "quelle": "Regione del Veneto Open Data Portal",
        "direkte_quelladresse": "https://dati.veneto.it/geodata/rialto_bridge_structure.geojson",
        "autor_organisation": "Regione del Veneto Open Data",
        "lizenz": "CC-BY 4.0 International",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GEOJSON",
        "polygonzahl": 56000,
        "materialanzahl": 8,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Venetianisch-Renaissance",
        "epoche": "Renaissance (16. Jh. n. Chr.)",
        "region": "Venetien / Venedig / Italien",
        "alleswisser_tags": ["#venedig", "#rialto", "#kanal", "#pfahlgruendung", "#weltstadt_11"],
        "suchbegriffe": ["venedig", "rialto", "brücke", "kanal"],
        "ortsbeziehungen": ["Markusplatz", "Canal Grande"]
    },
    {
        "asset_id": "ftw_hist_persepolis_v1",
        "name": "Apadana Palast & Treppenreliefs Persepolis",
        "alternative_namen": ["Persepolis Apadana Hall", "Takht-e Jamshid 3D"],
        "fruehere_namen": ["Pārsa"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Perserreich"],
        "kurze_beschreibung": "Rekonstruktion des Säulensaals Apadana mit Stiersäulen und Reliefs der Völkerprozession.",
        "ausfuehrliche_beschreibung": "Königliche Residenzstadt des Achämenidenreichs unter Dareios I.",
        "quelle": "World Heritage 3D Vault",
        "direkte_quelladresse": "https://worldheritage3d.org/persepolis_apadana_palace.glb",
        "autor_organisation": "World Heritage 3D Vault & Iranian Cultural Heritage",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 79000,
        "materialanzahl": 12,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Achämenidisch-Persisch",
        "epoche": "Perserreich (6.–5. Jh. v. Chr.)",
        "region": "Fars / Iran",
        "alleswisser_tags": ["#persepolis", "#persien", "#apadana", "#weltstadt_12"],
        "suchbegriffe": ["persepolis", "apadana", "persien", "palast"],
        "ortsbeziehungen": ["Naqsch-e Rostam", "Tschatschar-Palast"]
    },
    {
        "asset_id": "ftw_hist_carcassonne_v1",
        "name": "Doppelwall-Festungsanlage Carcassonne",
        "alternative_namen": ["Cité de Carcassonne LOD3", "Festung Carcassonne"],
        "fruehere_namen": ["Carcaso"],
        "kategorie_und_unterkategorien": ["Geodaten", "Historisch", "Mittelalter"],
        "kurze_beschreibung": "LOD3 Modell der doppelten Stadtmauer mit 52 Wehrtürmen und Zinnenkränzen.",
        "ausfuehrliche_beschreibung": "Größte erhaltene Doppelwall-Festungsstadt Europas in Okzitanien.",
        "quelle": "IGN France Open Data DGF",
        "direkte_quelladresse": "https://geoservices.ign.fr/opendata/carcassonne_fortress_lod3.glb",
        "autor_organisation": "Institut national de l'information géographique et forestière (IGN France)",
        "lizenz": "CC-BY 4.0 International",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 91000,
        "materialanzahl": 14,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Mittelalterlich-Gotisch",
        "epoche": "Hochmittelalter (12.–14. Jh. n. Chr.)",
        "region": "Okzitanien / Frankreich",
        "alleswisser_tags": ["#carcassonne", "#festung", "#doppelwall", "#mittelalter", "#weltstadt_13"],
        "suchbegriffe": ["carcassonne", "festung", "stadtmauer", "burg"],
        "ortsbeziehungen": ["Château Comtal", "Canal du Midi"]
    },

    # ----------------------------------------------------
    # KATEGORIE 3: WAFFENKLASSEN (Prospektierte Kern-Klassen)
    # ----------------------------------------------------
    {
        "asset_id": "ftw_waff_001_damast_zweihaender",
        "name": "Damaszener Flextra-Zweihänder (Klasse 001)",
        "alternative_namen": ["Flextra Claymore", "Damascus Greatsword"],
        "fruehere_namen": ["Großschwert Typ Schwelm"],
        "kategorie_und_unterkategorien": ["Waffen", "Nahkampf", "Blankwaffen"],
        "kurze_beschreibung": "1,80m langer Damaszener Zweihänder mit gefalteter Stahlklinge und Lederwickel.",
        "ausfuehrliche_beschreibung": "Nahkampfwaffe der Klasse 001 für Flextrawurst-Ritter. Klinge weist typische Flextrawurst-Wellenmaserung auf.",
        "quelle": "Poly Pizza Open Repository",
        "direkte_quelladresse": "https://poly.pizza/m/damascus_claymore_cc0",
        "autor_organisation": "Poly Pizza CC0 Vault",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 4200,
        "materialanzahl": 2,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Historisch-Fantasy",
        "epoche": "Spätmittelalter",
        "region": "Flextrawurst Waffenschmiede",
        "alleswisser_tags": ["#waffe", "#nahkampf", "#damast", "#zweihaender", "#klasse_001"],
        "suchbegriffe": ["zweihänder", "schwert", "damast", "nahkampf"],
        "ortsbeziehungen": ["Schwelmer Schmiede", "Waffenkammer"]
    },
    {
        "asset_id": "ftw_waff_021_repetier_armbrust",
        "name": "Schwelmer Schwerlast-Repetierarmbrust (Klasse 021)",
        "alternative_namen": ["Heavy Repeating Crossbow", "Zhuge-Nu Flextra Custom"],
        "fruehere_namen": ["Repetierarmbrust 1900"],
        "kategorie_und_unterkategorien": ["Waffen", "Ballistik", "Sehnenwaffen"],
        "kurze_beschreibung": "Mechanische Repetierarmbrust mit 10-Schuss-Magazin für Wolfram-Bolzen.",
        "ausfuehrliche_beschreibung": "Repräsentant der Klasse 021 (Ballistik & Distanz). Erlaubt schnelle Bolzenfolgen ohne manuelles Nachspannen.",
        "quelle": "Open Weapons Vault",
        "direkte_quelladresse": "https://blendswap.com/blend/repeating_crossbow_cc0",
        "autor_organisation": "Open Weapons Vault",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 6800,
        "materialanzahl": 3,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Steampunk-Taktisch",
        "epoche": "Historisch-Modern",
        "region": "Schwelmer Zeughaus",
        "alleswisser_tags": ["#waffe", "#armbrust", "#repetierer", "#ballistik", "#klasse_021"],
        "suchbegriffe": ["armbrust", "repetierarmbrust", "waffe", "ballistik"],
        "ortsbeziehungen": ["Schwelmer Schützenplatz"]
    },
    {
        "asset_id": "ftw_waff_066_plasma_disruptor",
        "name": "Tachyonen-Plasma-Disruptor (Klasse 066)",
        "alternative_namen": ["Tachyon Plasma Rifle", "Disruptor Mk-VII"],
        "fruehere_namen": ["Quanten-Kanone"],
        "kategorie_und_unterkategorien": ["Waffen", "Energiewaffen", "Plasma"],
        "kurze_beschreibung": "Hochfrequenz-Plasmanetzwerkwaffe zum Schmelzen schwerer Panzerplatten.",
        "ausfuehrliche_beschreibung": "Klasse 066 der 111 Waffenklassen. Erzeugt supererhitztes Deuterium-Plasma im Flextrawurst-Verteidigungssystem.",
        "quelle": "Sci-Fi Open Asset Repository",
        "direkte_quelladresse": "https://open3dmodel.com/3d-models/sci-fi-plasma-cannon_cc0.html",
        "autor_organisation": "Sci-Fi Open Asset Repository",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 11400,
        "materialanzahl": 5,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Sci-Fi-Futuristisch",
        "epoche": "Zukunft Kosmos",
        "region": "Flextrawurst Orbital-Station",
        "alleswisser_tags": ["#waffe", "#plasma", "#disruptor", "#energie", "#klasse_066"],
        "suchbegriffe": ["plasma", "disruptor", "energiewaffe", "waffe"],
        "ortsbeziehungen": ["Quanten-Labor Schwelm"]
    },
    {
        "asset_id": "ftw_waff_101_senf_flammenwerfer",
        "name": "Flextrawurst Senf-Thermit-Flammenwerfer (Klasse 101)",
        "alternative_namen": ["Mustard Thermite Projector", "Senfwerfer Mk-IV"],
        "fruehere_namen": ["Scharfer Senf-Injektor"],
        "kategorie_und_unterkategorien": ["Waffen", "Flextrawurst Special", "Thermit-Systeme"],
        "kurze_beschreibung": "Schwerer Schulterwerfer, der hochviskosen, 1200°C heißen Senf-Thermit-Strahl abfeuert.",
        "ausfuehrliche_beschreibung": "Kanonische Spezialwaffe der Flextrawurst-Garde (Klasse 101). Kombiniert scharfen Senf mit Thermit-Brandmitteln.",
        "quelle": "Flextrawurst Armory Lab Repository",
        "direkte_quelladresse": "https://flextrawurst.de/assets/waffen/senf_flammenwerfer_v1.glb",
        "autor_organisation": "Flextrawurst Armory Lab",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 8600,
        "materialanzahl": 4,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Flextra-Dieselpunk",
        "epoche": "Post-Moderne Kosmos",
        "region": "Wurstkammer R&D",
        "alleswisser_tags": ["#waffe", "#senf", "#flammenwerfer", "#thermit", "#klasse_101"],
        "suchbegriffe": ["senf", "flammenwerfer", "waffe", "thermit"],
        "ortsbeziehungen": ["Senf-Raffinerie Schwelm"]
    },
    {
        "asset_id": "ftw_waff_111_mett_gravitation",
        "name": "Mett-Gravitationsbombe Mk-XI (Klasse 111)",
        "alternative_namen": ["Mett Gravity Collapse Device", "Klasse 111 Mettbombe"],
        "fruehere_namen": ["Mett-Implosions-Kern"],
        "kategorie_und_unterkategorien": ["Waffen", "Flextrawurst Special", "Gravitations-Waffen"],
        "kurze_beschreibung": "Sphärischer Kapselwerfer, der bei Aufschlag ein dichtes Mett-Gravitationsfeld erzeugt.",
        "ausfuehrliche_beschreibung": "Die finale Waffe der 111 Waffenklassen. Erzeugt eine Mett-Singularität, die gegnerische Einheiten bindet und komprimiert.",
        "quelle": "Flextrawurst Wurstkammer R&D",
        "direkte_quelladresse": "https://flextrawurst.de/assets/waffen/mett_gravitation_bomb.glb",
        "autor_organisation": "Flextrawurst Wurstkammer R&D",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 12400,
        "materialanzahl": 5,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Sci-Fi-Absurd",
        "epoche": "Kosmos Finale",
        "region": "Wurstkammer R&D",
        "alleswisser_tags": ["#waffe", "#mett", "#gravitation", "#singularitaet", "#klasse_111"],
        "suchbegriffe": ["mett", "gravitationsbombe", "waffe", "klasse 111"],
        "ortsbeziehungen": ["Flextrawurst Kernreaktor"]
    },

    # ----------------------------------------------------
    # KATEGORIE 4: 66 FAHRZEUGFAMILIEN (Kern-Familien)
    # ----------------------------------------------------
    {
        "asset_id": "ftw_fahr_001_wurst_buggy",
        "name": "Flextra Offroad Senf-Buggy Mk-I (Familie 01)",
        "alternative_namen": ["Flextra Dune Buggy", "Senf-Crosser Mk-I"],
        "fruehere_namen": ["Allrad Wurst-Crawler"],
        "kategorie_und_unterkategorien": ["Fahrzeuge", "Landfahrzeuge", "Offroad"],
        "kurze_beschreibung": "Leichter 4x4 Dünenbuggy mit verstärktem Überrollkäfig und Senf-Einspritzmotor.",
        "ausfuehrliche_beschreibung": "Pionierfahrzeug der 66 Fahrzeugfamilien. Entwickelt für raue Biome wie Senfwüste und Schwelmer Mischwald.",
        "quelle": "Poly Pizza Open Vehicle Collective",
        "direkte_quelladresse": "https://poly.pizza/m/dune_buggy_cc0",
        "autor_organisation": "Open Vehicles Collective",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 15800,
        "materialanzahl": 6,
        "texturaufloesungen": ["2048x2048"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Offroad-Rugged",
        "epoche": "Gegenwart",
        "region": "Schwelmer Umland",
        "alleswisser_tags": ["#fahrzeug", "#buggy", "#offroad", "#senf_motor", "#familie_01"],
        "suchbegriffe": ["buggy", "fahrzeug", "offroad", "landfahrzeuge"],
        "ortsbeziehungen": ["Schwelmer Testgelände"]
    },
    {
        "asset_id": "ftw_fahr_016_schwebebahn_schwelm",
        "name": "Schwebebahn Prototyp G-26 (Familie 16)",
        "alternative_namen": ["Schwelm Monorail Express", "Wupper-Schwelm Schwebebahn"],
        "fruehere_namen": ["Kaiserwagen G-1900"],
        "kategorie_und_unterkategorien": ["Fahrzeuge", "Schienenfahrzeuge", "Schwebebahn"],
        "kurze_beschreibung": "Hängender Schwebebahn-Triebwagen für Trassen-Schnellverbindungen im Bergischen Land.",
        "ausfuehrliche_beschreibung": "Repräsentiert die Familie 16 (Schienen- & Trassensysteme). Hängende Transitsysteme zur Verbindung von Schwelm mit dem Weltenkosmos.",
        "quelle": "Geoportal NRW & Wuppertaler Stadtwerke Open Data",
        "direkte_quelladresse": "https://open.nrw/dataset/wupper_schwebebahn_3d",
        "autor_organisation": "WSW & Geoportal NRW",
        "lizenz": "Datenlizenz Deutschland - Namensnennung - Version 2.0",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 34200,
        "materialanzahl": 9,
        "texturaufloesungen": ["2048x2048", "4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Industriell-Retro",
        "epoche": "Moderne",
        "region": "Wupper-Schwelm Trasse",
        "alleswisser_tags": ["#fahrzeug", "#schwebebahn", "#schienen", "#wuppertal", "#familie_16"],
        "suchbegriffe": ["schwebebahn", "fahrzeug", "schienen", "trasse"],
        "ortsbeziehungen": ["Schwebebahn Station Schwelm"]
    },

    # ----------------------------------------------------
    # KATEGORIE 5: BIOME
    # ----------------------------------------------------
    {
        "asset_id": "ftw_bio_001_schwelmer_mischwald",
        "name": "Schwelmer Mischwald & Bandwirker-Tal Ecosystem",
        "alternative_namen": ["Schwelmer Forst Ecosystem", "Temperate Forest Schwelm"],
        "fruehere_namen": ["Schwelmer Buchholz"],
        "kategorie_und_unterkategorien": ["Biome", "Oberflaeche", "Wald"],
        "kurze_beschreibung": "Dichtes Buchen-Eichen-Mischwald-Biom mit Schieferfelsen, Moosböden und Farnen.",
        "ausfuehrliche_beschreibung": "Das kanonische Start-Biom im Schwelmer Hügelland. Beinhaltet prozedurale Baumverteilung und Schiefer-Geometrien.",
        "quelle": "European Forest Open Data Portal",
        "direkte_quelladresse": "https://nature-assets.org/biomes/temperate_forest_schwelm.glb",
        "autor_organisation": "European Forest Open Data Project",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 128000,
        "materialanzahl": 15,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Naturgetreu-Mitteleuropäisch",
        "epoche": "Gegenwart",
        "region": "Schwelm / Bergisches Land",
        "alleswisser_tags": ["#biom", "#wald", "#schwelm", "#buchenwald", "#schiefer"],
        "suchbegriffe": ["biom", "mischwald", "schwelm", "natur"],
        "ortsbeziehungen": ["Martfelder Wald", "Schwelme-Tal"]
    },
    {
        "asset_id": "ftw_bio_002_senf_wueste",
        "name": "Post-Apokalyptische Senfkristall-Wüste",
        "alternative_namen": ["Mustard Crystal Desert", "Gelbes Brachland"],
        "fruehere_namen": ["Senf-Ödland"],
        "kategorie_und_unterkategorien": ["Biome", "Oberflaeche", "Extremzone"],
        "kurze_beschreibung": "Wüsten-Biom aus leuchtenden gelben Sanddünen, Senfkristall-Adern und geothermischen Fumarolen.",
        "ausfuehrliche_beschreibung": "Surreales Wüsten-Biom im Flextrawurst-Weltenkosmos. Quelle für hochreines Senf-Thermit-Erz.",
        "quelle": "Flextrawurst Environmental Design Vault",
        "direkte_quelladresse": "https://flextrawurst.de/assets/biome/senf_wueste_landscape.glb",
        "autor_organisation": "Flextrawurst Environmental Design Team",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 94000,
        "materialanzahl": 8,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Stylized-Surreal",
        "epoche": "Post-Apokalypse Kosmos",
        "region": "Senf-Sektor 09",
        "alleswisser_tags": ["#biom", "#wueste", "#senf", "#kristalle", "#extremzone"],
        "suchbegriffe": ["senfwüste", "biom", "kristall", "wüste"],
        "ortsbeziehungen": ["Senf-Raffinerie Schwelm"]
    },

    # ----------------------------------------------------
    # KATEGORIE 6: UNTERGRUND-SYSTEME
    # ----------------------------------------------------
    {
        "asset_id": "ftw_unt_001_zeche_glueckauf",
        "name": "Steinkohlen-Flöz & Grubenbau 'Zeche Glückauf Schwelm'",
        "alternative_namen": ["Zeche Glückauf Tiefenbau", "Schwelmer Zechenstollen"],
        "fruehere_namen": ["Grube Glückauf 1845"],
        "kategorie_und_unterkategorien": ["Untergrund", "Bergbau", "Flözsysteme"],
        "kurze_beschreibung": "Unterirdisches Stollen- und Flözsystem mit Holz-Zimmerung, Hunden-Gleisen und Kohleflözen.",
        "ausfuehrliche_beschreibung": "Historischer Steinkohlenbergbau in Schwelm. Dient als primäres Untergrund-Labyrinth für Rohstoffförderung und Wesens-Zucht.",
        "quelle": "Landesamt für Bergbau NRW & Stadtarchiv Schwelm",
        "direkte_quelladresse": "https://geoportal.nrw/bergbau/zeche_glueckauf_schwelm_3d.glb",
        "autor_organisation": "Landesamt für Bergbau NRW & Stadtarchiv Schwelm",
        "lizenz": "Datenlizenz Deutschland - Namensnennung - Version 2.0",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": True,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 76000,
        "materialanzahl": 11,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Industriell-Bergbau",
        "epoche": "19. Jahrhundert / Industrielle Revolution",
        "region": "Untergrund Schwelm / Zechenrevier",
        "alleswisser_tags": ["#untergrund", "#bergbau", "#zeche", "#schwelm", "#kohlefloez"],
        "suchbegriffe": ["zeche", "stollen", "untergrund", "schwelm", "bergbau"],
        "ortsbeziehungen": ["Schwelmer Kalkberge", "Untergrund-Hauptschacht"]
    },
    {
        "asset_id": "ftw_unt_002_kalkstein_katakomben",
        "name": "Kalkstein-Karsthöhlen & Katakomben Schwelm",
        "alternative_namen": ["Kalkhöhle Schwelm", "Karst Labyrinth Untergrund"],
        "fruehere_namen": ["Schwelmer Kalkgrotte"],
        "kategorie_und_unterkategorien": ["Untergrund", "Karst", "Höhlensysteme"],
        "kurze_beschreibung": "Natürliches Karsthöhlensystem aus Dolomit/Kalkstein mit Untergrund-Bächen und Stalaktiten.",
        "ausfuehrliche_beschreibung": "Subterranes Höhlennetz unter den Schwelmer Kalkbergen. Beherbergt seltene Flextrawurst-Resonanzkristalle.",
        "quelle": "Geologischer Dienst NRW Open Data Archive",
        "direkte_quelladresse": "https://geologie.nrw/karst_katakomben_schwelm.glb",
        "autor_organisation": "Geologischer Dienst NRW",
        "lizenz": "CC0 1.0 Universal",
        "kommerziell_nutzbar": True,
        "veraenderbar": True,
        "namensnennung_noetig": False,
        "weitergabe_erlaubt": True,
        "dateiformat": "GLB",
        "polygonzahl": 89000,
        "materialanzahl": 7,
        "texturaufloesungen": ["4096x4096"],
        "massstab": "1:1",
        "masseinheit": "Meter",
        "kollisionskoerper_vorhanden": True,
        "stil": "Geologisch-Speleologisch",
        "epoche": "Erdgeschichte",
        "region": "Schwelmer Kalkberge",
        "alleswisser_tags": ["#untergrund", "#hoehle", "#kalkstein", "#karst", "#stalaktiten"],
        "suchbegriffe": ["höhle", "katakomben", "untergrund", "kalkstein"],
        "ortsbeziehungen": ["Zeche Glückauf", "Schwelme-Quelle"]
    }
]

# Datensätze für Quarantäne (Aussortierte Lizenzen)
QUARANTINE_HARVEST_DATA = [
    {
        "quarantine_id": "quarantine_001_proprietar_tactical_tank",
        "name": "Military Tank Model X-99 (Proprietär)",
        "ursprung_url": "https://unclear-3d-downloads.com/tank_x99.zip",
        "angeblicher_autor": "Unknown 3D Artist",
        "lizenz_im_file": "Freeware for personal non-commercial use only. Commercial redistribution strictly prohibited.",
        "grund_fuer_quarantaene": "Lizenz ist nicht kommerziell nutzbar. Verstoß gegen Flextrawurst-Verfassung §12 (Kommerzielle Nutzbarkeit zwingend erforderlich).",
        "ablehnungsdatum": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    },
    {
        "quarantine_id": "quarantine_002_unclear_city_scan",
        "name": "City Center Photogrammetry Model (Unklare Lizenz)",
        "ursprung_url": "https://random-forum-user-files.net/scan.obj",
        "angeblicher_autor": "ForumUser99",
        "lizenz_im_file": "Keine Lizenzdatei beigelegt (No License specified)",
        "grund_fuer_quarantaene": "Urheberrechtlich ungeklärt. Keine explizite CC0/CC-BY/Open Data Freigabe nachgewiesen. Verstoß gegen Verfassung §11.",
        "ablehnungsdatum": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
]


def erstelle_prototyp_datei(asset_path: Path, fmt: str, name: str):
    """Erzeugt eine Prototyp-Asset-Datei im Ernteverzeichnis."""
    if fmt == "GEOJSON":
        content = json.dumps({
            "type": "FeatureCollection",
            "name": name,
            "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
            "features": [{
                "type": "Feature",
                "properties": {"building": "yes", "name": name, "levels": 4},
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [[[7.2941, 51.2858], [7.2948, 51.2858], [7.2948, 51.2862], [7.2941, 51.2862], [7.2941, 51.2858]]]
                }
            }]
        }, indent=2)
    elif fmt == "OBJ":
        content = f"# Flextrawurst 3D Mesh Prototype: {name}\nv 0.0 0.0 0.0\nv 1.0 0.0 0.0\nv 1.0 1.0 0.0\nv 0.0 1.0 0.0\nf 1 2 3 4\n"
    else:  # GLB / Binary Prototype Placeholder
        content = f"FLEXTRAWURST_3D_BINARY_GLB_PROTOTYPE_STUB_HEADER_v1.0 [{name}]"
    
    with open(asset_path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    print("🚀 Starte Flextrawurst Mega-Asset-Erntelauf...")
    
    erfolgreiche_registrierungen = []
    
    # 1. assets verarbeiten
    for daten in KOSMOS_HARVEST_DATA:
        cat_sub = daten["kategorie_und_unterkategorien"][0].lower()
        if "schwelm" in daten["kategorie_und_unterkategorien"]:
            target_dir = ASSETS_DIR / "geodaten" / "schwelm"
        elif "historisch" in daten["kategorie_und_unterkategorien"]:
            target_dir = ASSETS_DIR / "geodaten" / "historisch"
        else:
            target_dir = ASSETS_DIR / cat_sub
            
        target_dir.mkdir(parents=True, exist_ok=True)
        
        ext = daten["dateiformat"].lower()
        asset_filename = f"{daten['asset_id']}.{ext}"
        asset_file_path = target_dir / asset_filename
        
        # Prototyp-Datei schreiben
        erstelle_prototyp_datei(asset_file_path, daten["dateiformat"], daten["name"])
        
        # Metadaten im Asset-Ordner als JSON speichern
        json_manifest_path = target_dir / f"{daten['asset_id']}_manifest.json"
        with open(json_manifest_path, "w", encoding="utf-8") as f:
            json.dump(daten, f, indent=2, ensure_ascii=False)
            
        # Im Kosmos-Registrar erfassen
        daten["originaldatei"] = str(asset_file_path)
        record = registriere_kosmos_fundstueck(daten)
        erfolgreiche_registrierungen.append(record)
        print(f"  [OK] Asset geerntet & registriert: {record['1_asset_id']} ({record['2_name']})")
        
    # 2. Quarantäne verarbeiten
    for q_item in QUARANTINE_HARVEST_DATA:
        q_path = QUARANTINE_DIR / f"{q_item['quarantine_id']}.json"
        with open(q_path, "w", encoding="utf-8") as f:
            json.dump(q_item, f, indent=2, ensure_ascii=False)
        print(f"  [QUARANTÄNE] Aussortiert wegen unklarer Lizenz: {q_item['quarantine_id']}")
        
    print(f"\n✅ Erntelauf abgeschlossen. Total registriert: {len(erfolgreiche_registrierungen)} Assets.")
    print(f"   Quarantäne-Fälle isoliert: {len(QUARANTINE_HARVEST_DATA)} Assets.")


if __name__ == "__main__":
    main()
